// src/routeTree.gen.ts

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TagEditorRouteImport } from './routes/tag-editor'
import { Route as IndexRouteImport } from './routes/index'

const TagEditorRoute = TagEditorRouteImport.update({
  id: '/tag-editor',
  path: '/tag-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tag-editor': typeof TagEditorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tag-editor': typeof TagEditorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tag-editor': typeof TagEditorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tag-editor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tag-editor'
  id: '__root__' | '/' | '/tag-editor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TagEditorRoute: typeof TagEditorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tag-editor': {
      id: '/tag-editor'
      path: '/tag-editor'
      fullPath: '/tag-editor'
      preLoaderRoute: typeof TagEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TagEditorRoute: TagEditorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
